#ifndef QENGINEUTILITIES_API_H
#define QENGINEUTILITIES_API_H

#include <QtCore/qglobal.h>

#if defined(QENGINEUTILITIES_LIBRARY)
#  define QENGINEUTILITIES_API Q_DECL_EXPORT
#else
#  define QENGINEUTILITIES_API Q_DECL_IMPORT
#endif

#endif // QENGINEUTILITIES_API_H